# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\schrma\Documents\python\03-fitparser\ui\MainGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 940)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelMainPic = QtWidgets.QLabel(self.centralwidget)
        self.labelMainPic.setGeometry(QtCore.QRect(850, 30, 191, 111))
        self.labelMainPic.setText("")
        self.labelMainPic.setPixmap(QtGui.QPixmap("../images/fenix3.jpg"))
        self.labelMainPic.setScaledContents(True)
        self.labelMainPic.setObjectName("labelMainPic")
        self.mTextTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.mTextTB.setGeometry(QtCore.QRect(550, 50, 256, 151))
        self.mTextTB.setObjectName("mTextTB")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 230, 881, 541))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(51, 51, 486, 143))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mTestPB = QtWidgets.QPushButton(self.widget1)
        self.mTestPB.setObjectName("mTestPB")
        self.verticalLayout.addWidget(self.mTestPB)
        self.mProcessPB = QtWidgets.QPushButton(self.widget1)
        self.mProcessPB.setObjectName("mProcessPB")
        self.verticalLayout.addWidget(self.mProcessPB)
        self.ParseToFileButton = QtWidgets.QPushButton(self.widget1)
        self.ParseToFileButton.setObjectName("ParseToFileButton")
        self.verticalLayout.addWidget(self.ParseToFileButton)
        self.mBackupPB = QtWidgets.QPushButton(self.widget1)
        self.mBackupPB.setObjectName("mBackupPB")
        self.verticalLayout.addWidget(self.mBackupPB)
        self.mGetDataFromWatchPB = QtWidgets.QPushButton(self.widget1)
        self.mGetDataFromWatchPB.setObjectName("mGetDataFromWatchPB")
        self.verticalLayout.addWidget(self.mGetDataFromWatchPB)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget1)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.widget1)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 3, 1, 1)
        self.m_UseDefaultFolderCB = QtWidgets.QCheckBox(self.widget1)
        self.m_UseDefaultFolderCB.setObjectName("m_UseDefaultFolderCB")
        self.gridLayout_2.addWidget(self.m_UseDefaultFolderCB, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.menuHelp.addAction(self.actionVersion)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Heartrate"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Steps"))
        self.mTestPB.setText(_translate("MainWindow", "TestButton"))
        self.mProcessPB.setText(_translate("MainWindow", "ShowPlot"))
        self.ParseToFileButton.setText(_translate("MainWindow", "ParseToFile"))
        self.mBackupPB.setText(_translate("MainWindow", "Backup"))
        self.mGetDataFromWatchPB.setText(_translate("MainWindow", "Get Data from Watch"))
        self.label_2.setText(_translate("MainWindow", "End Date"))
        self.label.setText(_translate("MainWindow", "Start Date"))
        self.m_UseDefaultFolderCB.setText(_translate("MainWindow", "Use default Folder"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

